kind: Service
apiVersion: v1
metadata:
  #Service name
  name: cliente-service
spec:
  selector:
    app: cart-blockms
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
